### ISSUE TITLE
Something is not quite right (Async)

### ISSUE THREAD

**Issue by th2000125** [DawnFire-Realms/CommunityBridge#219] opened 2015-02-04 18:09 UTC
Hey I'm getting a error on the new version,

    [16:02:38 WARN]: Exception in thread "Craft Scheduler Thread - 6"
    [16:02:38 WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 105
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException
    at org.communitybridge.main.WebApplication$1.run(WebApplication.java:229)
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
    ​
    There is also a start up error, but there are no previous errors to be seen.

    [15:47:52] [Server thread/INFO]: [CommunityBridge] Enabling CommunityBridge v2.6.0.000
    [15:47:52] [Server thread/INFO]: [CommunityBridge] Permissions System: GroupManager
    [15:47:52] [Server thread/ERROR]: [CommunityBridge] Simple synchronization disabled due to prior errors.
    ​
    ^ it is obviously not disabled and changed my rank but it seems to be having a few issues
    Thanks for your time and the new update!

**Comment by TEKAA92** [comment] 2015-02-04 18:15
I'm not at home atm, but is the first error at start up or does it appear later ?

**Comment by TEKAA92** [comment] 2015-02-04 19:19
Can you add your log to this convo? I would like to see where the error might have occured, since I experience no such error myself. I see that you use Groupmanager, wich I do not. That might be a plausible cause.

**Comment by TEKAA92** [comment] 2015-02-04 19:20
Can you add your log to this convo? I would like to see where the error might have occured, since I experience no such error myself. I see that you use Groupmanager, wich I do not. That might be a plausible cause.

@th2000125

**Comment by th2000125** [comment] 2015-02-04 21:55
Is there a more private method I can use? as there is sensitive information inside that can't be publicly disclosed.
Thanks for the quick response!

**Comment by TEKAA92** [comment] 2015-02-04 22:00
send me a pm, or you can just copy paste the start up log, and some of the log before the error and the error itself and some lines further. Leave out the sensitive stuff.

I just need to se how the plugin communicates with the rest of your plugins and if the error might be caused by another plugin.

**Comment by th2000125** [comment] 2015-02-05 18:31
http://www.mediafire.com/download/xsyxbfoqvnaosdx/latest.log
^ just removed all the IP's and so on
Thank you!

**Comment by TEKAA92** [comment] 2015-02-05 18:37
I will test out a few things, 
Try to use the 1.7 jar, cause it should work with the 1.8 client, and see if it generates the same errors.

**Comment by th2000125** [comment] 2015-02-05 18:38
I will do

**Comment by TEKAA92** [comment] 2015-02-05 19:05
The reason you get the CommunityBridge error is due to some error at the startup that makes CB  disable Simple Synchronization.

I see that your server generates 2 errors before CommunityBridge.

NetherRoofProtect, wich gets disabled anyway so try to remove it and do a new startup, and
Citizens. 

Try to remove NetherRoofProtect and Citizens, and then do a start up and see if the error occurs.

**Comment by th2000125** [comment] 2015-02-05 19:06
Okay am trying now

**Comment by TEKAA92** [comment] 2015-02-05 19:17
Do the error occur now?

**Comment by th2000125** [comment] 2015-02-05 19:19
Removed DTL traders, citizens, and roofprotect and I'm still getting the error

"[19:13:22 ERROR]: [CommunityBridge] Simple synchronization disabled due to prior errors."

"[19:16:40 INFO]: th2000125[/] logged in with entity id 121 at ([Vanilla] 5564.411708271654, 102.0, 6217.433420851549)
[19:16:40 INFO]: [Essentials] Lag Notice - Slow Permissions System (GroupManager) Response - Request took over 57.64ms!
[19:16:40 WARN]: Exception in thread "Craft Scheduler Thread - 1" 
[19:16:40 WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 53
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.communitybridge.main.WebApplication$1.run(WebApplication.java:229)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more"

**Comment by th2000125** [comment] 2015-02-05 19:20
Its detecting the Database but its moving (like before) me and others who are not member into member

**Comment by TEKAA92** [comment] 2015-02-05 19:20
Hmmm... And when you used the 1.7 version. the sam thing happens?

**Comment by th2000125** [comment] 2015-02-05 19:29
I tried it with the carbon plugin with 1.7 and its happening

**Comment by th2000125** [comment] 2015-02-05 19:29
Whats the build you are using?

**Comment by TEKAA92** [comment] 2015-02-05 19:30
It sounds to me that there is either a config error, or another plugin that disables CB's synchronization

**Comment by th2000125** [comment] 2015-02-05 19:32
Well its accessing the database, even when it says somethings gone wrong because it can find registered players.

**Comment by TEKAA92** [comment] 2015-02-05 19:36
Yes, it connects and all, but when the simple synchronization is disabled, it will generate the error above.

It says that a prior error is the cause of the disabling. And I can not see any other errors in the log that might cause this, hence a possible config or plugin that interferes

**Comment by th2000125** [comment] 2015-02-05 19:39
I don't mind sending the config, and I will try removing plugins until its only got this left.

**Comment by TEKAA92** [comment] 2015-02-05 19:45
Let me have a look on the config, and remember to leave out the password and such :)

**Comment by th2000125** [comment] 2015-02-05 19:51
http://www.mediafire.com/download/objo1xefpc6bq64/config.yml
^ Thanks for reminding me :)

**Comment by TEKAA92** [comment] 2015-02-05 19:58
Try to set simple Synchronization to false and start the server

**Comment by th2000125** [comment] 2015-02-05 20:03
No error on start up! :D 

But this is still happening
[20:02:03 INFO]: th2000125[/] logged in with entity id 122 at ([Vanilla] 5566.142536289526, 87.76858102247299, 5963.33912220311)
[20:02:03 WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[20:02:03 WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 53
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.communitybridge.main.WebApplication$1.run(WebApplication.java:229)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by TEKAA92** [comment] 2015-02-05 20:12
Why that nullpointer though. lol
Looking through the config to see why.

**Comment by th2000125** [comment] 2015-02-05 20:14
I'm trying spigot latest build.

**Comment by th2000125** [comment] 2015-02-05 20:18
[20:18:24 INFO]: [Essentials] Lag Notice - Slow Permissions System (GroupManager) Response - Request took over 68.407ms!
[20:18:24 WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[20:18:24 WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 53
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.communitybridge.main.WebApplication$1.run(WebApplication.java:229)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by th2000125** [comment] 2015-02-07 18:37
If it helps I tried 1.7 again and the errors don't seem to be appearing.
But my players only want 1.8 so this is a problem :/

**Comment by jflory7** [comment] 2015-02-12 01:31
I'm poking my head in to say that I'm having a similar issue that has made the current version unusable for me. My stacktrace is as follows:

```
[20:26:21 WARN]: Exception in thread "Craft Scheduler Thread - 793" 
[20:26:21 WARN]: org.apache.commons.lang.UnhandledException: Plugin CommunityBridge v2.6.0.000 generated an exception while executing task 87888
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at org.communitybridge.main.WebApplication.synchronizeGroupsSecondaryGameToWeb(WebApplication.java:777)
        at org.communitybridge.main.WebApplication.synchronizeGroupsSecondary(WebApplication.java:709)
        at org.communitybridge.main.WebApplication.synchronizeGroups(WebApplication.java:343)
        at org.communitybridge.synchronization.PlayerSynchronizationDispatcher.playerStateBaseSynchronization(PlayerSynchronizationDispatcher.java:67)
        at org.communitybridge.synchronization.PlayerSynchronizationDispatcher.synchronizePlayer(PlayerSynchronizationDispatcher.java:41)
        at org.communitybridge.main.WebApplication$1.run(WebApplication.java:229)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

All of my server staff keep losing their ranks as a result, and on the XenForo forum, they are set to the "Unregistered / Unconfirmed" group. I'm going to downgrade for the time being.

**Comment by TEKAA92** [comment] 2015-02-12 11:05
Alright! Sorry for not doing much this weekend, I have been away.

I will do a thoroughly debugging today, and find out 100% where the error is. 

@jflory7 Wich permission plugin are you using?

**Comment by TEKAA92** [comment] 2015-02-12 13:13
@jflory7 are you able to upload your config for CB? If so, remember to remove the sensitive information.

**Comment by jflory7** [comment] 2015-02-12 13:20
@TEKAA92 
I am using zPermissions with a database for my permissions. My CB configuration is as follows:

```
#                  Community Bridge Configuration File
# -----------------------------------------------------------------------------

#                             General Settings
# -----------------------------------------------------------------------------
general:
  # Log level controls the degree of detail that is sent to the console/log
  # The possible settings are (in order of quietest to noisiest:
  #   info, config, fine, finer, finest, all
  # - During configuration, I recommend using 'config'.
  # - During normal operation, I recommend using 'info'.
  # - If you want to see the notifications that the synchronize and reminder
  #   notices have been sent, use 'fine'
  # - During troubleshooting of problems, set this to either finest or all.
  log-level: info

  # Allow plugin metrics to start up for this plugin. Please turn on
  # metrics! It helps plugin authors determine what features to include!
  # For more details see:
  # http://dev.bukkit.org/bukkit-plugins/communitybridge-fm/pages/why-plugin-metrics/
  # Enable/Disable for all plugins by editing plugins/PluginMetrics/config.yml
  # and setting 'opt-out' to false.
  plugin-metrics: true

  # Turns on the achievements (rewards) system. See achievements.yml for more
  # information.
  use-achievements: false

  # Set the unit of measurement for sync and reminder scheduling. Options are:
  # ticks, seconds, minutes, hours, or days. Note that this applies to both
  # auto-sync-every and auto-remind-every.
  auto-every-unit: minutes

  # This is a timer that will check and sync all data with your database at a
  # set interval. Otherwise group and player statistics will only be
  # synchronized when the player joins and leaves the Minecraft server.
  auto-sync: true

  # The interval for the auto-sync timer, this should not be set any lower than
  # 20 minutes.
  auto-sync-every: 20

  # Enables/disables synchronization during join and quit events. Recommend both
  # being set to true.
  sync-during-join: true
  sync-during-quit: true

  # NOTE: PermissionsBukkit will not create groups on the fly. So any groups you
  #       specify in the linking or synchronization sections must already
  #       exist. It will not be feasible to fix this issue due to the lack of
  #       a real API.
  # NOTE: zPermissions will not create groups on the fly. So any groups you
  #       specify in the linking or synchronization sections must already
  #       exist. That is, you need to have used: permissions group <group>
  #       create. Further, zPermissions lacks a real API. A player's group
  #       assignment can fail without CommunityBridge being aware of the
  #       failure.

  # The permissions system you're using. A permissions system is required for
  # the following features:
  # * Group Synchronization (both primary and secondary)
  # * Unregistered/Registered group assignment (sub-features of 'linking')
  # Current Options are: bPerms, GroupManager, PermsBukkit, PEX, Vault,
  #                      zPermissions.
  permissions-system: zPermissions

  # If ~APPURL~ appears in a message in messages.yml, it will be replaced with
  # this:
  application-url: http://crystalcraftmc.com

  # Set the date format for any of the dates used by CommunityBridge.
  date-format: "yyyy-MM-dd hh:mm:ss a"

#                             Database Settings
# -----------------------------------------------------------------------------
# Please ensure if you run your Minecraft server on a remote host
# that your MySQL server allows REMOTE connections. This WILL NOT WORK unless
# your MySQL server is configured to allow connections from the machine that
# your Minecraft server is running on. If you don't know what that means,
# consult your hosting provider on how to configure your MySQL server correctly.
# All of this information should be the same server and database used by your
# web-application...
database:
  # Hostname for your MySQL Server
  hostname:

  # MySQL Port
  port:

  # Database Name
  name:

  # Database Username
  username:

  # Database Password
  password:

  # SQL binding address
  # Normally you won't need to set anything here.
  # Recommended setting is blank.
  # If needed the local binding address for the SQL client can be set here.
  # Use 'minecraft' to use the address set in the server.properties.
  binding-address:

#                             Player Linking Settings
# -----------------------------------------------------------------------------
# Settings associated with linking a Minecraft player with a web application's
# user. As this feature is a prerequisite for all other features, it cannot
# be disabled.
player-user-linking:
  # Use this to specify which method you are using: uuid, name, or both.
  # uuid - Players are identified by uuid in your web application's database.
  # name - Players are identified by player name in your web application's database.
  # both - Communitybridge will try both ways before giving up.
  linking-method: name

  # If you want the player disconnected from the game if they haven't
  # registered, then set this to true. They will be shown the
  # link-unregistered-player message (in message.yml) on the disconnected
  # screen.
  kick-unregistered: false

  # This is a timer that will notify unregistered users to register every few
  # minutes.
  auto-remind: true

  # The interval for the auto-remind timer, this should be no less than
  # 5-10 minutes. Note that this uses the units specified above in
  # auto-every-unit.
  auto-remind-every: 10

  # Set these to true to inform players when they log in if they're linked to
  # the web application. These correspond to the link-unregistered-player and
  # link-registered-player messages in messages.yml.
  notify-registered-player: false
  notify-unregistered-player: true

  # If you have a permissions system and you want the player to be placed
  # in a group based on (un)registered status, set the following.
  # If left blank the setting won't be used. If a group-synchronization
  # feature is turned on, the 'registered-player-group' won't be used.
  unregistered-player-group: default
  registered-player-group: Members
  notify-player-of-group: true

  # If you want a player to be added to the 'registered-player-group' ONLY if:
  # * they are a member of the unregistered-player-group OR
  # * they have no assigned groups
  # then set this to true.
  registered-former-unregistered-only: true

  # If you want a player to be added to the 'unregistered-player-group' if they
  # are no longer registered, set this to true.
  unregister-former-registered: true

  # This is where we specify how to associate a Minecraft player with a web
  # application user. We do this by matching up the player name with a name
  # stored in the web application's database.
  #
  # If you want your players to use the same name on both the server and the
  # web application, then you will need to provide the table and column
  # information where the web application relates its user IDs with the user's
  # name/login ID/login/username.
  #
  # If you want to allow them to use a different name on the web application,
  # you need to add a custom field or column to your web application's database
  # for their minecraft name and specify below where the minecraft name is stored
  # in the web application's database.

  # The name of the table which contains the columns:
  table-name: xf_user

  # Column on the table that contains the user ID. Typically, the column will be
  # named something like user_id or member_id and contains a unique number for each
  # user.
  user-id-column: user_id

  # If the player name is stored in a key-value pair of columns instead of
  # its own column, set this to true:
  uses-key: false

  # If you set 'linking-uses-key' to false, then set this to the column that
  # the minecraft uuid or playername is stored in. Otherwise, leave it empty.
  identifier-column: username

  # If you set 'linking-uses-key' to true, then set the key column, value
  # column, and the key-name here. Otherwise, leave these fields empty.
  key-name:
  key-column:
  value-column:

# Used either for requiring and avatar or rewarding the existence of an avatar.
app-avatar-config:
  enabled: false
  # Table that contains the avatar column
  table-name:
  # Column on the avatar table that contains the user ID.
  user-id-column:
  # Column on the avatar table that contains the avatar information. If this
  # column contains data, the user is assumed by CommunityBridge to have an
  # avatar.
  avatar-column:

# Used for post count awards or for requiring a post count.
app-post-count-config:
  enabled: true
  # Table that contains the post count column
  table-name: xf_user
  # Column on the avatar table that contains the user ID.
  user-id-column: user_id
  # Column containing the user's post count.
  post-count-column: message_count

#                             Requirements
# -----------------------------------------------------------------------------
requirement:
  # Set this to true to require an avatar to be set to access the game.
  # Requires app-avatar-config settings to be enabled and configured correctly.
  avatar: false
  # Require the player to have at least this many posts before being able to
  # play. Requires app-post-count-config settings to be enabled and configured
  # correctly.
  post-count:
    enabled: false
    minimum: 0

#                             Statistics Tracking
# -----------------------------------------------------------------------------
# In general, to make this work, your web application will need to support
# custom profile fields or a similar feature. CommunityBridge will put the
# information in the database. It is up to you to configure your web application
# so that it displays the information.
statistics:
  # Enables statistics tracking. Nothing will be tracked unless you also enable
  # at least one of the trackers below.
  enabled: false
  # Name of the table to insert the tracking information on to.
  table-name:
  # Name of the column that contains the player's User ID on the table.
  user-id-column:
  # Set this to true if data on the table is stored in key-value pairs.
  uses-key: false

  # If uses-key is true, set these as well. These settings are not used if
  # uses-key is false.
  key-column:
  value-column:

  # Some web applications require an insert the first time a custom profile
  # field is filled with data (SMF, for example). If that's the case, enable
  # this and provide the required information.
  insert:
    enabled: false
    # Options are: generic and smf.
    method: generic

    # Required for the 'smf' method, ignored for other methods. Most likely id_theme.
    theme-id-column: id_theme

    # Required for the 'smf' method, ignored for other methods. Most likely value is 1.
    theme-id: 1

  # Individual trackers
  # -------------------
  trackers:
    # Below each tracker can be enabled and configured. For each tracker:
    # * If uses key is true, set column-or-key-name to the key name OR
    #   If uses key is false, set column-or-key-name to the column name
    # For some trackers, there is a formatted version as well. For those
    # trackers, the formatted version is optional. If you wish to use the
    # formatted version, set the formatted-column-or-key-name appropriately.
    # If set, the formatted column will be filled in with a human readable
    # string.

    # Online Status: Show a player is playing on the server in the forums.
    online-status:
      enabled: false
      column-or-key-name:
      # Set this to what should be stored in the field when the user is online.
      online-value:
      # Set this to what should be stored in the field when the user is offline.
      offline-value:

    # Last Online: Record the time that player was last online
    last-online:
      enabled: false
      # Numeric column, should be able to store a 32 bit integer. Will be seconds since epoch.
      column-or-key-name:
      # String (varchar, etc.) column at least 60 characters in length.
      formatted-column-or-key-name:

    # Game Time: Record how much time the player has played.
    # Requires the last-online tracker to be turned on as well.
    game-time:
      enabled: false
      # Numeric column, should be able to store a 32 bit integer. Time played in seconds.
      column-or-key-name:
      formatted-column-or-key-name:

    # Player's current level
    level:
      enabled: false
      # Numeric column, a single byte will be sufficient in most cases.
      column-or-key-name:

    # Player's current progress toward next level
    current-xp:
      enabled: false
      # Numeric floating point column.
      column-or-key-name:
      # String column with at least 4 characters capacity.
      formatted-column-or-key-name:

    # Player's XP total
    total-xp:
      enabled: false
      # Numeric column, capable of storing a 32 bit integer.
      column-or-key-name:

    # Player's current health
    health:
      enabled: false
      # Numeric column, a single byte should be sufficient.
      column-or-key-name:

    # Lifeticks; the amount of time the player has been alive.
    lifeticks:
      enabled: false
      # Numeric column, capable of storing a 32 bit integer.
      column-or-key-name:
      # String field with at least 100 characters of storage.
      formatted-column-or-key-name:

    # Wallet. The amount of money the player currently has. REQUIRES VAULT.
    wallet:
      enabled: false
      # Numeric column capable of storing a "double" floating point number.
      column-or-key-name:

#                     Web Application Group Configuration
# -----------------------------------------------------------------------------
#
# Some terminology:
# - Primary group: A group setting such that the setting can only be set to
#   exactly one group. Most web applications have such a feature. Very few
#   permissions systems have such a feature. A given player/user can be a member
#   of only one primary group at a time.
#   NOTE: If you wish to utilize the primary group synchronization feature and
#         your permissions system does not support primary groups, then you must
#         list groups you wish to be synchronized into the web applications
#         primary group field in the "groups-treated-as-primary" setting (see
#         the synchronization options below). The permissions systems that this
#         applies to are: bPerms, PermissionsBukkit, PermissionsEx, and Vault.
# - Secondary group(s): A group setting such that the setting can be set to
#   multiple groups or none. A given player/user can be a member multiple
#   secondary groups at a time in addition to being member of a single
#   primary group.

# This section describes to Communitybridge how the web application stores
# user group/role information.
app-group-config:
  # If the web application has a primary group/role feature, configure it here.
  primary:
    enabled: true
    # The table that contains the primary group ID.
    table-name: xf_user

    # The column on the table that contains the user ID.
    user-id-column: user_id

    # If the primary group is stored in a key-value pair, set this to true.
    uses-key: false

    # The column that the primary group ID is stored in. If uses-key is true,
    # this is the column that the "value" of the key-value pair is stored in.
    group-id-column: user_group_id

    # If you set uses-key to true, then set the following three settings:
    # Key name for the key-value pair.
    key-name:
    # Column that the key name is in
    key-column:

  # If the web application has a secondary groups feature, configure it here.
  secondary:
    enabled: true
    # The table that contains the secondary groups.
    table-name: xf_user

    # The column on the table that contains the user ID.
    user-id-column: user_id

    # Storage method. Set to one of the following:
    # - single: All the group ids in a single row & column separated by the
    #           delimiter specified below.
    # - key-value: All the group ids are in a single row & column, separated
    #              by the delimiter specified below, on a table that stores
    #              its data in key-value pairs
    # - multiple-key-value: Group IDs are stored on a table of key-value pairs,
    #                    where the key name can appear in multiple rows.
    # - junction: The table can contain multiple rows for a given user_id,
    #             each with their own group_id.
    storage-method: single

    # The column that the group ID(s) are stored in:
    # (For the key-value method, this is the 'value' column)
    group-id-column: secondary_group_ids

    # For single-column or key-value storage methods, the delimiter/separator
    # that separates the group IDs:
    # (ignored for junction and multiple-key-value storage method)
    group-id-delimiter: ','

    # For the key-value storage method:
    # (ignored for the junction and single methods)
    # Key name for the key-value pair.
    key-name:
    # Column that the key name is in
    key-column:

    # This applies to the junction storage method. If there are additional columns on
    # the junction table that need to be set to a value different from the table default
    # add the column name and value to this list.
    additional-columns:
      # group_leader: 0
      # user_pending: 0

# Simple Synchronization Configuration
# NOTE: If you wish to utilize the primary group synchronization feature and
#       your permissions system does not support primary groups, then you must
#       list groups you wish to be synchronized into the web applications
#       primary group field in the "groups-treated-as-primary" setting. The
#       permissions systems that this applies to are: bPerms, PermissionsBukkit,
#       PermissionsEx, Vault, and zPermissions.
simple-synchronization:
  # Set this to true for simple synchronization
  enabled: true

  # Controls the "direction" of synchronization.
  # Options are: two-way, web-application, or minecraft.
  # - two-way: Changes on either side are synchronized to the other.
  # - web-application: Changes made in the web-application are
  #   synchronized to the Minecraft server.
  # - minecraft: Changes made in Minecraft are synchronized to the
  #   web-application.
  direction: two-way

  # If player hasn't been seen before on server, CommunityBridge will use this
  # setting to determine the direction of the synchronization. 'web-application'
  # is the only option available at this time.
  first-direction: web-application

  # Set this to true if you want the player to be notified when their primary
  # group changes.
  primary-group-change-notify: true

  # This is a safety net. Since CommunityBridge directly modifies group
  # membership information, there is a risk that a misconfiguration could
  # cause the main administrative account (e.g. super-user) of a webapp to not
  # have administrative privileges to the forum, potentially leaving the forum
  # in a state where it cannot be administered. To protect against this
  # possibility, provide the user-id of the main administrative account of the
  # web application here. Generally, this is the account created when the web
  # application was installed. For this user-id, group changes will not be
  # synchronized from Minecraft to the web application, that is, the
  # synchronization for this user will be as if direction was set to
  # 'web' (see above). Be absolutely sure this user-id is your super-user
  # all-access administrative account.
  super-user-user-id: '1'

  # If you're using primary group synchronization and a permissions system that
  # does NOT have the notion of primary groups (bPerms, PermissionsBukkit,
  # PermissionsEx, Vault) you must list permission group names that you wish to
  # be synchronized into the user's primary group field on the web application
  # here. Be sure to include these groups in the group-mapping as well.
  # Sample: groups-treated-as-primary: [guest, member, premium]
  #         note that the brackets are required.
  groups-treated-as-primary: ['default', 'Members', 'Trial-Mods', 'Moderators', 'Admins', 'Owners']

  # If you have groups that are secondary groups on the web application that
  # you wish to be treated as if they are primary on your permissions system
  # (that is, these groups will be mutually exclusive), List them here.
  # Sample: groups-treated-as-primary: [guest, member, premium]
  #         note that the brackets are required.
  webapp-secondary-groups-treated-as-primary: ['Chat Moderators']

  # List groups and group IDs to be synchronized here. On the left side of
  # the colon put a web application's group ID. On the right side of the colon
  # put the corresponding permissions group name. Only list group IDs and
  # group names you wish to be synchronized.

  # NOTE: Regarding ladders(promotions/inherited groups): Either ALL of the
  #       groups that are part of a ladder need to have entries on this table
  #       and have corresponding group on the web application or NONE of them
  #       should be on this list. It may be that you want to use the
  #       unregistered/registered group settings instead.
  group-mapping:
    '1' : 'default'
    '2' : 'Members'
    '29' : 'Chat-Mods'
    '6' : 'Trial-Mods'
    '5' : 'Moderators'
    '4' : 'Admins'
    '3' : 'Owners'

ban-synchronization:
  enabled: false

  # Controls the "direction" of synchronization.
  # Options are: two-way, web-application, or minecraft.
  # - two-way: Changes on either side are synchronized to the other.
  # - web-application: Changes made in the web-application are
  #   synchronized to the Minecraft server.
  # - minecraft: Changes made in Minecraft are synchronized to the
  #   web-application.
  direction: two-way

  # Method options:
  # - table: Banned users will be inserted and deleted from a table that is a list of bans
  # - user: A column on the users/members table designates whether a user is banned.
  # - group: Specify a web-application group whose members are banned. Specify whether
  #          the group is a primary or secondary group and configure app-group-config
  #          above as appropiate.
  method: table

  # Group method settings
  # Group type is either primary or secondary
  group-type:
  banned-group:

  # Name of the table that holds ban information for your web application. Only needed for
  # user and table methods.
  table-name:

  # Column that contains the user ID of the banee. Only needed for the user and table methods.
  banned-user-id-column:

  # Settings for the user method. Only needed if method above is set to user
  # The value parameters can be strings, numbers, whatever your web application
  # uses to indicate the user is banned or not.
  ban-column:
  value-banned:
  value-notbanned:

  # Settings for table method. Only needed if method above is 'table'. Set
  # options that seem relevant to your web application.
  # The column containing the reason for the ban. Leave blank if your web
  # application does not support this.
  ban-reason-column:
  # The column containing the ban start time (systime expected). Leave blank
  # if your application does not support this.
  ban-start-column:
  # The column containing the ban end time (systime expected). Leave blank
  # if your application does not support this.
  ban-end-column:
  # The column containing ban-group-id. Leave blank if your web application
  # does not support this.
  ban-group-id-column:
  # The ban-group-id. Leave blank if your web application does not support this.
  ban-group-id:
```

**Comment by TEKAA92** [comment] 2015-02-12 13:37
@jflory7 

It looks like your error is due to simple synchronization and that the group id's aren't matching between either website & config or game & config, and you get an ArrayList error.

I see that under group-mapping that you have an interesting setup. Is there a reason to why you have it set up as you have with one being '29' and the rest in single digits?

I noticed now that in the primary mapping, that you do not have listed Chat-mods as a primary group:
 groups-treated-as-primary: ['default', 'Members', 'Trial-Mods', 'Moderators', 'Admins', 'Owners']

Why not? is this intentional?

**Comment by TEKAA92** [comment] 2015-02-12 14:01
@jflory7 
To be more specific, its when the plugin tries to synchronize the secondary group aka: Chat-Mods to the website that you get the error.

**Comment by jflory7** [comment] 2015-02-12 14:06
@TEKAA92 
Hmmm, that's strange. I just wonder why it works on 2.5.2, but when I upgraded to 2.6.0, it started throwing this error.

As for the `group-mapping`, that's just how XenForo handles the user groups. All of the single digit user groups were groups that were created earlier in the history of my site's existence. The Chat-Moderators group was added more recently, and as a result, it has a higher ID number, since XenForo never completely removes a group from the database, I suppose (i.e. even though I deleted group 18, it will not recreate a new group as ID 18, but ID 19 instead).

As for the Chat-Mods group not being treated as a primary group, it is not supposed to be a priamry group, but rather only a secondary group. Normally, I have it set up so a player might be a registered member or a paid rank, and then a Chat-Mod would have those permissions + a little bit extra. On my site specifically, it grants them access to a special forum. Adding it as a primary group isn't an option as it would require me to structure my in-game hierarchy in a way that would mean giving ALL of my Chat-Mods either too many or too little permissions, since they all have different ranks in addition to being Chat-Mods.

**Comment by TEKAA92** [comment] 2015-02-12 14:15
@jflory7 
Alright, that answered everything. 

Regarding why the error shows up in 2.6.0, I have no idea, I did no changes to the synchronization section, since this was doing just fine. I do not get the error myself, but I will look further into the code to see if I can find a solution to this.

Thank you for your patience!

**Comment by terokorp** [comment] 2015-02-12 14:27
I get exacly same error message.
Changes which I have made to config: https://gist.github.com/terokorp/bff80230fcd0f00ee4e8
(general section: default, database: ok, player-user-linking: ok, all others disabled)
When logging in, it tells "Registered account, linked to forums", so connection works, but something is still broken.

**Comment by TEKAA92** [comment] 2015-02-12 14:59
@jflory7 
Ok, I did some debugging and have a test version ready for you to test and see if the errors still appears.

Dropbox link:
https://www.dropbox.com/s/6m783ks65p41rwo/CommunityBridge-test.jar?dl=0

**Comment by terokorp** [comment] 2015-02-12 15:17
That version works on my server

**Comment by TEKAA92** [comment] 2015-02-12 15:18
@terokorp 
Good! thanks for the feedback

**Comment by jflory7** [comment] 2015-02-12 17:29
@TEKAA92 
It's showing me that the file was moved or deleted.

**Comment by TEKAA92** [comment] 2015-02-12 17:30
I changed the name of it. Here's the new link

https://www.dropbox.com/s/pw8v5lwwof60td9/CommunityBridge.jar?dl=0

**Comment by TEKAA92** [comment] 2015-02-13 09:54
@th2000125 @jflory7 
Updated the plugin to fix the synchronization error.

I will close this issue if none of you are experiencing error on this anymore.

**Comment by th2000125** [comment] 2015-02-13 10:26
Hi @TEKAA92 Thanks for your help!
I don't know if its the config but unregistered users are still not being moved to member :/
Although all the errors have stopped! thank you so much!

**Comment by TEKAA92** [comment] 2015-02-13 11:07
@th2000125 Alright! Awesome :)

**Comment by jflory7** [comment] 2015-02-13 15:01
@TEKAA92 
I just updated to 2.6.0B on my server, and it seems the issue is resolved. I tried typing `/cbsync` on a few players to test, and nothing unexpected happened.

I think it's safe to say it's fixed! If I encounter any issues, I will either reopen this issue or file a new one.

Thanks for the quick fix and friendly support!

**Comment by TEKAA92** [comment] 2015-02-14 00:54
Im glad to hear that! :)

**Closed by TEKAA92** 2015-02-14 00:54 UTC
